export const viewAllD = [
  {
    id: 1,
    img: "/categories/FreshFlowers.webp",
    title: "Fresh Flowers",
    Size: "",
    tag: "All Categories",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 2,
    img: "/categories/Foliages.webp",
    title: "Foliages",
    Size: "",
    tag: "All Categories",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 3,
    img: "/categories/SpecialFlowers.webp",
    title: "Special Flowers",
    Size: "",
    tag: "All Categories",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 4,
    img: "/categories/Fillers.webp",
    title: "Fillers",
    Size: "",
    tag: "All Categories",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 5,
    img: "/categories/Bouquets.jpeg",
    title: "Bouquets",
    Size: "",
    tag: "All Categories",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 6,
    img: "/categories/Plants.webp",
    title: "Plants",
    Size: "",
    tag: "All Categories",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
];
export const FreshFlowersD = [
  {
    id: 1,
    img: "/categories/FreshFlowers.webp",
    title: "Fresh Flowers",
    tag: "Fresh Flowers",
    desc: "Learn More",
    link1: "",
    linkw:"godfgogle.com",
    link2: "",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity:"1 piece",
    color:
      "Anthurium-White , Anthurium-Red , Anthurium-Peach , Anthurium-Green , Anthurium-Brown , Anthurium-Pink , Anthurium-Bi-Color",
  },
  {
    id: 2,
    img: "/categories/Foliages.webp",
    title: "Foliages",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity:"1 piece",
    color:
      "Anthurium-White , Anthurium-Red , Anthurium-Peach , Anthurium-Green , Anthurium-Brown , Anthurium-Pink , Anthurium-Bi-Color",
    tag: "Fresh Flowers",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 3,
    img: "/categories/SpecialFlowers.webp",
    title: "Special Flowers",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity:"1 piece",
    color:
      "Anthurium-White , Anthurium-Red , Anthurium-Peach , Anthurium-Green , Anthurium-Brown , Anthurium-Pink , Anthurium-Bi-Color",
    tag: "Fresh Flowers",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 4,
    img: "/categories/Fillers.webp",
    title: "Fillers",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity:"1 piece",
    color:
      "Anthurium-White , Anthurium-Red , Anthurium-Peach , Anthurium-Green , Anthurium-Brown , Anthurium-Pink , Anthurium-Bi-Color",
    tag: "Fresh Flowers",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 5,
    img: "/categories/Bouquets.jpeg",
    title: "Bouquets",
    Size: "",
    tag: "Fresh Flowers",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
];
export const FoliagesD = [
  {
    id: 1,
    img: "/categories/FreshFlowers.webp",
    title: "Fresh Flowers",
    Size: "",
    tag: "Foliages",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 2,
    img: "/categories/Foliages.webp",
    title: "Foliages",
    Size: "",
    tag: "Foliages",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 3,
    img: "/categories/SpecialFlowers.webp",
    title: "Special Flowers",
    Size: "",
    tag: "Foliages",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 4,
    img: "/categories/Fillers.webp",
    title: "Fillers",
    Size: "",
    tag: "Foliages",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
];
export const ForFillersD = [
  {
    id: 1,
    img: "/categories/FreshFlowers.webp",
    title: "Fresh Flowers",
    Size: "",
    tag: "For Fillers",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 2,
    img: "/categories/Foliages.webp",
    title: "Foliages",
    Size: "",
    tag: "For Fillers",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 3,
    img: "/categories/SpecialFlowers.webp",
    title: "Special Flowers",
    Size: "",
    tag: "For Fillers",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
];

export const specialFlowersD = [
  {
    id: 1,
    img: "/categories/FreshFlowers.webp",
    title: "Fresh Flowers",
    Size: "",
    tag: "Special Flowers",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 2,
    img: "/categories/Foliages.webp",
    title: "Foliages",
    Size: "",
    tag: "Special Flowers",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
];
export const BouquetsD = [
  {
    id: 1,
    img: "/categories/FreshFlowers.webp",
    title: "Fresh Flowers",
    Size: "",
    tag: "Bouquets",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 2,
    img: "/categories/Foliages.webp",
    title: "Foliages",
    Size: "",
    tag: "Bouquets",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 3,
    img: "/categories/SpecialFlowers.webp",
    title: "Special Flowers",
    Size: "",
    tag: "Bouquets",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
];
export const PlantsD = [
  {
    id: 1,
    img: "/categories/FreshFlowers.webp",
    title: "Fresh Flowers",
    Size: "",
    tag: "Plants",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 2,
    img: "/categories/Foliages.webp",
    title: "Foliages",
    Size: "",
    tag: "Plants",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
  {
    id: 3,
    img: "/categories/SpecialFlowers.webp",
    title: "Special Flowers",
    Size: "",
    tag: "Plants",
    link1: "",
    linkw:"google.com",
    link2: "",
  },
];
