export const viewAllD = [
  {
    id: 1,
    img: "/categories/FreshFlowers.webp",
    title: "Fresh Flowers",
    Size: "",
    tag: "All Categories",
    link1: "#Fresh",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 2,
    img: "/categories/Foliages.webp",
    title: "Foliages",
    Size: "",
    tag: "All Categories",
    link1: "#foliages",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 3,
    img: "/categories/SpecialFlowers.webp",
    title: "Special Flowers",
    Size: "",
    tag: "All Categories",
    link1: "#specialFlowers",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 4,
    img: "/categories/Fillers.webp",
    title: "Fillers",
    Size: "",
    tag: "All Categories",
    link1: "#fillers",
    linkw: "google.com",
    link2: "",
  },
  // {
  //   id: 5,
  //   img: "/categories/Bouquets.jpeg",
  //   title: "Bouquets",
  //   Size: "",
  //   tag: "All Categories",
  //   link1: "",
  //   linkw: "google.com",
  //   link2: "",
  // },
  // {
  //   id: 6,
  //   img: "/categories/Plants.webp",
  //   title: "Plants",
  //   Size: "",
  //   tag: "All Categories",
  //   link1: "",
  //   linkw: "google.com",
  //   link2: "",
  // },
];
export const FreshFlowersD = [
  {
    id: 1,
    img: "/fresh-flowers/Anthurium.png",
    title: "Anthurium",
    tag: "Fresh Flowers",
    desc: "Learn More",
    link1: "",
    linkw: "godfgogle.com",
    link2: "",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "1 piece",
    color:
      "Anthurium-White , Anthurium-Red , Anthurium-Peach , Anthurium-Green , Anthurium-Brown , Anthurium-Pink , Anthurium-Bi-Color",
  },
  {
    id: 2,
    img: "/fresh-flowers/Asiatic-Lilly-Oriental-Lilly.png",
    title: "Asiatic Lilly/ Oriental Lilly",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Lilly-White , Lilly-Pink , Lilly-Orange , Lilly-Yellow , Lilly-Red",
    tag: "Fresh Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 3,
    img: "/fresh-flowers/Bird-Of-Paradise.png",
    title: "B.O.P(Bird Of Paradise)",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch / piece",
    color:
      "B.O.P-Orange",
    tag: "Fresh Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 4,
    img: "/fresh-flowers/Carnations.png",
    title: "Carnations",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Carnation-Light Pink , Carnation-Dark pink , Carnation-Purple , Carnation-Peach , Carnation-Red , Carnation-White , Carnation-Yellow , Carnation-Green, Carnation-Orange , Carnation-Purple",
    tag: "Fresh Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 5,
    img: "/fresh-flowers/Hybrid-Crysanthemum.jpg",
    title: "Hybrid Crysanthemum",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Hybrid Crysanthemum-White ,Hybrid Crysanthemum-Pink , Hybrid Crysanthemum-Yellow , Hybrid Crysanthemum-Purple , Double Shaded color, Hybrid Crysanthemum-White ,Hybrid Crysanthemum-Green , Hybrid Crysanthemum-Pink , Hybrid Crysanthemum-Yellow",
    tag: "Fresh Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 6,
    img: "/fresh-flowers/Gerbera.png",
    title: "Gerbera",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Gerbera-White , Gerbera-Yellow , Gerbera-Orange , Gerbera-Light Pink , Gerbera-Dark Pink , Gerbera-Red , Gerbera-Peach",
    tag: "Fresh Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 7,
    img: "/fresh-flowers/Heliconia-Red.png",
    title: "Heliconia Red",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Heliconia Red",
    tag: "Fresh Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 8,
    img: "/fresh-flowers/Heliconia_Sexy_Pink.jpg",
    title: "Hanging Heliconia_Sexy_Pink",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch / Piece",
    color:
      "Heliconia_Sexy_Pink",
    tag: "Fresh Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 10,
    img: "/fresh-flowers/Orchid.jpeg",
    title: "Orchid",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Orchid-White , Orchid-Purple , Orchid-Blue , Orchid-Yellow",
    tag: "Fresh Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 11,
    img: "/fresh-flowers/Orchid-Mokara.png",
    title: "Orchid Mokara",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Orchid Mokara-Red , Orchid Mokara-Green",
    tag: "Fresh Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 12,
    img: "/fresh-flowers/Rose-Dutch.png",
    title: "Rose Dutch",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Rose Avalanche-White , Rose Avalanche-Peach , Rose Avalanche-Sweet , Rose Gold Strike-Yellow , Rose Noblesse-Light Pink , Rose Corvette-Orange",
    tag: "Fresh Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
];
export const FoliagesD = [
  {
    id: 1,
    img: "/foliages/Monster.png",
    title: "Monster Leaves",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 2,
    img: "/foliages/Areca.jpg",
    title: "Areca Palm",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "10Stalks/Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 3,
    img: "/foliages/Cypress.png",
    title: "Cypress",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "10Stalks/Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 4,
    img: "/foliages/Ping-ong.png",
    title: "Ming Fern/ Ping Pong/ Ball Asperagus /MyrioCladus",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 5,
    img: "/foliages/Asperagus.png",
    title: "Asperagus",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "30Stalks/Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 6,
    img: "/foliages/Dracena.png",
    title: "Dracena",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "10Stalks/Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 7,
    img: "/foliages/Song-Of-India.png",
    title: "Song Of India/ Jamica",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "5Stalks/Bunch",
    color:
      "Green-Yellow",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 8,
    img: "/foliages/Bop-Leaves.png",
    title: "Bop Leaves",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "20Stalks/Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 9,
    img: "/foliages/Eucalyptus.png",
    title: "Eucalyptus",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "10Stalks/Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 10,
    img: "/foliages/Leather-Leaves.jpg",
    title: "Leather Leaves",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "10Stalks/Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 11,
    img: "/foliages/Xenuda.png",
    title: "Xenuda",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "5Stalks/Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 12,
    img: "/foliages/Kamini.png",
    title: "Kamini",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 13,
    img: "/foliages/Ribbon-Grass.png",
    title: "Ribbon Grass",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Green",
    tag: "Foliages",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
];
export const ForFillersD = [
  {
    id: 1,
    img: "/fillers/Statice.jpg",
    title: "Statice",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Statice-White , Statice-Blue , Statice-Purple , Statice-Yellow , Statice-Pink , Statice-Peach , Statice-lavender",
    tag: "For Fillers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 2,
    img: "/fillers/Gypsophila.jpg",
    title: "Gypsophila",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Gypsophila-White",
    tag: "For Fillers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 3,
    img: "/fillers/Limonium.jpeg",
    title: "Limonium",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Limonium-Purple , Limonium-Violet",
    tag: "For Fillers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 4,
    img: "/fillers/Gladiolus.png",
    title: "Gladiolus",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Gladiolus-White , Gladiolus-Red",
    tag: "For Fillers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 5,
    img: "/fillers/TubeRose.png",
    title: "Tube Rose",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "TubeRose-White",
    tag: "For Fillers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 6,
    img: "/fillers/Golden-Rod.png",
    title: "Golden Rod",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Golden Rod-Yellow",
    tag: "For Fillers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 7,
    img: "/fillers/Alstromeria.png",
    title: "Alstromeria",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Alstromeria-White , Alstromeria-Pink , Alstromeria-Yellow , Alstromeria-Red",
    tag: "For Fillers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 8,
    img: "/fillers/Daisy.jpeg",
    title: "Daisy's",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "White Daisy , Blue Daisy , Yellow Daisy",
    tag: "For Fillers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
];

export const specialFlowersD = [
  {
    id: 1,
    img: "/special-flower/Amaranthus.jpg",
    title: "Amaranthus",
    Size: "S, M, L, XL, XXL",
    availability: "Pre-Orde",
    quantity: "Bunch",
    color:
      "Amaranthus-Green, Amaranthus-Peach, Amaranthus-Red, Amaranthus-White,",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 2,
    img: "/special-flower/Tulips.png",
    title: "Tulips",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Tulips-White , Tulips-Red , Tulips-Yellow , Tulips-Pink , Tulips-Purple",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 3,
    img: "/special-flower/Hydrangea.png",
    title: "Hydrangea",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Hydrangea-White , Hydrangea-Pink , Hydrangea-Blue , Hydrangea-Purple",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 4,
    img: "/special-flower/Sunflower-Yellow.jpg",
    title: "Sunflower",
    Size: "S, M, L, XL, XXL",
    availability: "Year Round",
    quantity: "Bunch",
    color:
      "Sunflower-Yellow",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 5,
    img: "/special-flower/Brassica.jpg",
    title: "Brassica",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Brassica-White , Brassica-Pink , Brassica-Purple , Brassica-Green",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 6,
    img: "/special-flower/Cigar.jpeg",
    title: "Cigar",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Cigar-red",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 7,
    img: "/special-flower/Spray.png",
    title: "Spray Carnations",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Spray Carnations-White , Spray Carnations-Pink , Spray Carnations-Yellow , Spray Carnations-Orange , Spray Carnations-Peach , Spray Carnations-Red, Spray Carnations-Orange , Spray Carnations-Purple , Spray Carnations-Green",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 8,
    img: "/special-flower/Disbuds.jpg",
    title: "Disbuds",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Disbuds-White , Disbuds-Pink , Disbuds-Green , Disbuds-Yellow , Disbuds-Light Purple , Disbuds-Light Orange",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 9,
    img: "/special-flower/Snapdragon.png",
    title: "Snapdragon",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Snapdragon-White , Snapdragon-Yellow , Snapdragon-Pink , Snapdragon-Peach , Snapdragon-Dark pink , Snapdragon-Purple ,",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 10,
    img: "/special-flower/Rattles.jpeg",
    title: "Rattles Shaker",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Rattlesnake-Yellow , Rattlesnake-Pink",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 11,
    img: "/special-flower/Sweet.jpg",
    title: "Sweet williams",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Sweet Williams-White , Sweet Williams-Pink , Sweet Williams-Blue , Sweet Williams-Purple",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 12,
    img: "/special-flower/Eustoma.png",
    title: "Eustoma",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Eustoma-White , Eustoma-Pink , Eustoma-Blue , Eustoma-Purple , Eustoma-Peach , Eustoma-Green",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 13,
    img: "/special-flower/Guzmania.jpg",
    title: "Guzmania",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Guzmania-Yellow , Guzmania-Pink , Guzmania-Orange",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 14,
    img: "/special-flower/Shampoo_Ginger.png",
    title: "Shampoo_Ginger",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "Shampoo_Ginger",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
  {
    id: 15,
    img: "/special-flower/CURCUMA.jpeg",
    title: "CURCUMA",
    Size: "S, M, L, XL, XXL",
    availability: "Seasonal",
    quantity: "Bunch",
    color:
      "CURCUMA",
    tag: "Special Flowers",
    link1: "",
    linkw: "google.com",
    link2: "",
  },
];
// export const BouquetsD = [
//   {
//     id: 1,
//     img: "/categories/FreshFlowers.webp",
//     title: "Fresh Flowers",
//     Size: "",
//     tag: "Bouquets",
//     link1: "",
//     linkw: "google.com",
//     link2: "",
//   },
//   {
//     id: 2,
//     img: "/categories/Foliages.webp",
//     title: "Foliages",
//     Size: "",
//     tag: "Bouquets",
//     link1: "",
//     linkw: "google.com",
//     link2: "",
//   },
//   {
//     id: 3,
//     img: "/categories/SpecialFlowers.webp",
//     title: "Special Flowers",
//     Size: "",
//     tag: "Bouquets",
//     link1: "",
//     linkw: "google.com",
//     link2: "",
//   },
// ];
// export const PlantsD = [
//   {
//     id: 1,
//     img: "/categories/FreshFlowers.webp",
//     title: "Fresh Flowers",
//     Size: "",
//     tag: "Plants",
//     link1: "",
//     linkw: "google.com",
//     link2: "",
//   },
//   {
//     id: 2,
//     img: "/categories/Foliages.webp",
//     title: "Foliages",
//     Size: "",
//     tag: "Plants",
//     link1: "",
//     linkw: "google.com",
//     link2: "",
//   },
//   {
//     id: 3,
//     img: "/categories/SpecialFlowers.webp",
//     title: "Special Flowers",
//     Size: "",
//     tag: "Plants",
//     link1: "",
//     linkw: "google.com",
//     link2: "",
//   },
// ];
